In [9]:
import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)
import os

## Read data

In [17]:
# [!] use nrows here for reading sample transactions 
new_merchant_transactions = pd.read_csv('all/new_merchant_transactions.csv',parse_dates=['purchase_date'], nrows=1000)
historical_transactions = pd.read_csv('all/historical_transactions.csv',parse_dates=['purchase_date'], nrows=1000)
merchant = pd.read_csv('all/merchants.csv').drop(['category_1', 'category_2'], 1)# Since category column exist in transaction data already, we filter them out before merge into transaction data 

# Combine two transactions data into one 
# (not sure if we want to merge new and historical transactions, so just put it here)
transactions = pd.concat([new_merchant_transactions, historical_transactions], axis = 0) 
# transactions = transactions[transactions.authorized_flag== 'Y']

# merge transaction + merchant data 
transactions = pd.merge(transactions, merchant, on = 'merchant_id', how = 'left')# Merge transaction + merchant data

## Features

In [18]:
# Transform featrues 
def transfrom_features(df):
    """
    Transform features, for example, extrac month from purchase date, get dummys from category
    """
    # Month
    df['purchase_month'] = df.purchase_date.dt.month
    
    return df

In [40]:

def agg_transaction_features(df):
    """
    In this function, we input raw transaction data (assume we join merchant data)
    And output aggregate features by card_id 
    """
    
    # Aggregate features -- purchase related 
    agg_purchase = df.groupby(by='card_id').agg(
        {'purchase_amount': ['count','sum','mean']
        , 'merchant_id': ['nunique']
        , 'installments': ['sum']
        , 'purchase_date': ['min', 'max']
        }).reset_index() 
          
    agg_purchase.columns = ["_".join(x) for x in agg_purchase.columns.ravel()] 
    
    return agg_purchase

## Aggregate by card_id

In [42]:
df = transfrom_features(transactions)
agg_transaction_features(df)

,card_id_,installments_sum,merchant_id_nunique,purchase_date_min,purchase_date_max,purchase_amount_count,purchase_amount_sum,purchase_amount_mean
0,C_ID_0682c61725,0,2,2018-03-05 09:39:03,2018-04-09 11:49:24,2,-1.293963,-0.646981
1,C_ID_086fe1da99,22,22,2018-03-01 14:25:48,2018-04-29 11:54:06,22,-13.099166,-0.595417
2,C_ID_0a6ceeffcc,0,20,2017-11-02 12:39:37,2017-12-22 13:52:37,21,-14.855736,-0.707416
3,C_ID_0cb8b21999,12,9,2018-03-13 17:11:35,2018-03-21 13:03:36,9,-5.172486,-0.574721
4,C_ID_0e171c1b48,3,72,2017-02-25 09:38:46,2018-02-27 13:48:19,301,-213.355250,-0.708821
5,C_ID_0e764b1f60,8,6,2018-03-03 10:18:46,2018-04-20 19:23:12,6,-4.029269,-0.671545
6,C_ID_18c53fe97a,23,16,2018-03-02 15:32:48,2018-04-30 20:12:32,16,-9.186728,-0.574171
7,C_ID_1c8decd066,0,3,2018-03-07 14:15:04,2018-03-20 16:14:12,3,-2.095462,-0.698487
8,C_ID_1f236c50e6,12,11,2018-03-01 18:25:39,2018-04-27 20:24:42,11,-3.269078,-0.297189
9,C_ID_2158fb5770,8,8,2018-03-18 09:30:54,2018-04-27 10:46:33,8,-3.668708,-0.458588
10,C_ID_241a01e9d9,9,2,2018-04-22 19:19:08,2018-04-22 19:34:11,2,-0.756465,-0.378232
11,C_ID_2b9ed150e4,16,16,2018-03-07 13:06:36,2018-04-19 13:10:50,16,-8.548432,-0.534277
12,C_ID_2bba08c2c4,8,8,2018-03-09 18:09:02,2018-04-28 23:55:05,8,-4.212788,-0.526598
13,C_ID_2e90fec40e,0,7,2017-12-01 10:59:37,2018-01-31 23:53:27,7,-4.652268,-0.664610
14,C_ID_3820db9e00,0,9,2017-06-03 12:06:24,2017-07-15 12:33:13,9,-5.940596,-0.660066
15,C_ID_38bd7c7f78,19,19,2018-03-04 16:36:16,2018-04-30 10:16:27,19,-11.847879,-0.623573
16,C_ID_3ab838c7d8,0,32,2018-03-03 12:08:32,2018-04-30 12:09:43,32,-21.493787,-0.671681
17,C_ID_3d5f4353dc,35,28,2018-03-04 12:49:39,2018-04-21 13:26:51,28,-14.898877,-0.532103
18,C_ID_415bb3a509,4,4,2018-03-07 09:43:21,2018-04-26 14:08:44,4,-2.350116,-0.587529
19,C_ID_44ffea4679,6,4,2018-03-02 13:40:06,2018-04-03 21:25:57,4,-2.241339,-0.560335
20,C_ID_458deb9a23,0,1,2018-01-10 09:14:48,2018-01-10 09:14:48,1,-0.671775,-0.671775
21,C_ID_46d755bb3a,8,6,2018-03-01 14:17:36,2018-04-23 14:58:37,7,-4.497165,-0.642452
22,C_ID_48fb13e70f,95,43,2017-06-01 18:51:35,2018-02-23 09:37:27,82,-46.557468,-0.567774
23,C_ID_4d164e5926,0,4,2018-04-07 12:02:58,2018-04-09 09:45:54,4,-2.769536,-0.692384
24,C_ID_4e6213e9bc,0,55,2017-01-20 09:16:43,2018-02-28 17:00:08,412,-299.515225,-0.726979
25,C_ID_5004574fff,6,6,2018-03-06 13:54:27,2018-04-25 09:06:44,7,-3.298785,-0.471255
26,C_ID_5037ff576e,133,80,2017-01-06 13:36:12,2017-12-25 21:03:22,123,-44.395333,-0.360938
27,C_ID_528351ab5c,7,6,2018-03-08 11:55:44,2018-04-22 06:01:13,7,-4.979666,-0.711381
28,C_ID_56eb88fdac,14,13,2018-03-04 21:02:09,2018-04-23 17:47:24,13,-6.522889,-0.501761
29,C_ID_56fb263b38,19,17,2018-03-09 10:58:16,2018-04-30 08:06:48,17,-9.642768,-0.567222
...,...,...,...,...,...,...,...,...
51,C_ID_af99e70f6a,4,3,2018-03-10 12:59:49,2018-03-12 14:48:18,3,-1.842521,-0.614174
52,C_ID_b05b8a1bc3,0,4,2018-03-05 09:24:58,2018-03-26 15:44:00,4,-2.843377,-0.710844
53,C_ID_b1f2ab5e6b,35,29,2018-03-01 11:27:45,2018-04-29 17:28:26,29,-15.109654,-0.521023
54,C_ID_b25d492593,0,4,2018-04-13 11:54:46,2018-04-21 18:58:35,4,-2.627145,-0.656786
55,C_ID_bb43f4f97a,0,8,2018-03-08 18:26:30,2018-04-30 22:15:09,9,-6.306101,-0.700678
56,C_ID_be71a60d23,0,13,2018-03-01 05:47:19,2018-04-30 17:44:44,13,-9.032091,-0.694776
57,C_ID_c08881d71e,0,16,2017-10-06 15:50:09,2017-11-25 14:45:42,17,-12.002832,-0.706049
58,C_ID_c0e5bea5e3,0,9,2018-03-27 17:52:53,2018-04-17 12:11:56,9,-6.145498,-0.682833
59,C_ID_c239d2062e,0,16,2018-03-09 13:34:30,2018-04-24 13:28:13,16,-4.300272,-0.268767
60,C_ID_c2b034498d,3,3,2018-03-14 14:51:32,2018-04-16 21:25:36,3,-1.919457,-0.639819
61,C_ID_c5bf64ecbd,31,16,2018-03-05 15:55:27,2018-04-23 09:48:29,16,-5.371121,-0.335695
62,C_ID_c63e242d14,0,15,2017-12-01 20:46:19,2018-01-28 07:30:01,15,-9.945207,-0.663014
63,C_ID_cb123befc4,8,8,2017-12-03 18:49:32,2018-01-11 09:34:18,8,-5.520725,-0.690091
64,C_ID_cb2269c52d,63,25,2018-03-09 14:26:28,2018-04-28 12:39:21,27,-12.081210,-0.447452
65,C_ID_cde58e2519,0,10,2018-02-07 11:07:47,2018-03-28 19:06:37,10,-6.443113,-0.644311
66,C_ID_d15cd87e37,0,22,2018-03-03 16:03:57,2018-04-22 23:00:34,23,-1.332130,-0.057919
67,C_ID_da88b91cbc,11,12,2018-03-02 13:06:12,2018-04-29 12:10:18,12,-6.975697,-0.581308
68,C_ID_e30251715d,0,12,2018-03-01 05:26:26,2018-04-30 16:20:56,13,-8.100402,-0.623108
69,C_ID_e30fc0a37d,11,9,2018-03-17 00:53:43,2018-04-18 08:24:16,9,-6.138345,-0.682038
70,C_ID_e4d60467c2,29,18,2018-03-16 16:13:18,2018-04-21 13:53:12,20,-12.868660,-0.643433
71,C_ID_e6928d4b95,10,9,2018-03-09 03:58:56,2018-04-30 15:37:19,10,-6.356305,-0.635630
72,C_ID_ec7f7416c1,38,32,2018-02-01 16:58:43,2018-03-26 11:42:37,33,-20.292433,-0.614922
73,C_ID_ef55cf8d4b,36,22,2018-03-01 14:26:52,2018-04-22 15:00:27,22,5.653665,0.256985
74,C_ID_f0653560a1,0,18,2018-03-10 14:16:22,2018-04-16 15:46:33,18,-12.269568,-0.681643
75,C_ID_f4f2312ef3,15,12,2018-03-15 12:36:38,2018-04-28 16:33:28,12,-7.852179,-0.654348
76,C_ID_faacef6d77,0,3,2018-02-01 09:42:32,2018-02-12 15:17:21,4,-2.720204,-0.680051
77,C_ID_fb0875cd28,0,7,2018-03-05 15:16:31,2018-04-19 12:50:40,7,-4.618459,-0.659780
78,C_ID_fba2b3a1cf,8,8,2018-02-04 17:56:49,2018-03-31 11:01:38,8,-5.575843,-0.696980
79,C_ID_fc8e41b9cf,175,53,2017-07-14 18:23:51,2018-02-25 12:13:50,150,-80.773391,-0.538489
80,C_ID_fd55871fd8,7,5,2018-02-03 19:46:47,2018-02-23 15:16:18,5,-1.174322,-0.234864